
sudo: required
dist: trusty
language: node_js
node_js:
  - "9"
before_install:
  - npm install -g rollup yarn
  - yarn -V
install:
  - yarn install
before_script:
  - rollup -c
script:
  - npm test
  - npm run lint
